GraphQLError: revert `originalError` to be nullable
Fix #3340
Partial revert of #3333
Were reverted due to conflict with Apollo Server, see
https://github.com/apollographql/apollo-server/issues/5843