Error: make 'path' and 'locations' enumerable only if present (#1305)
* Error: make 'path' and 'locations' enumerable only if present

Also cleanup tests from 'undefined' and 'containSubset'.

* expect subset of errors