GraphQLError: major refactoring to be more in line with v16
Shouldn't change anything but since we changed type of `originalError`
it should be treated as feature change.