GraphQLError: use enumerable properties
Since we now provide `toJSON` method it means it's finally safe to use
enumerable properties and convert class into idiomatic TS.
Previously TS didn't check `Object.defineProperties` so we could only
only define optional properties on this class.